### ISSUE TITLE
Object reference not set to an instance of an object. (500)

### ISSUE THREAD

**Issue by Crashdummyy** [tfsaggregator/tfsaggregator-webhooks#11]
Hey There,

My Webhook responds everytime with ( Object reference not set to an instance of an object. (500) )
Exception.

How can that Exception be thrown?

`            var userStory = self.Parent;

                userStory["Microsoft.VSTS.Scheduling.CompletedWork"] =
                    userStory.Children.Sum(task => task.GetField<double>("Microsoft.VSTS.Scheduling.CompletedWork", 0d));
                userStory["Microsoft.VSTS.Scheduling.OriginalEstimate"] =
                    userStory.Children.Sum(taskk => taskk.GetField<double>("Microsoft.VSTS.Scheduling.OriginalEstimate", 0d));
`

The Code is very Simple and even provides an default Value.

**Comment by jessehouwing** [comment]
I suspect the item doesn't have a parent. Thus self.parent is null.

On Nov 24, 2017 13:08, "Simon" <notifications@github.com> wrote:

Hey There,

My Webhook responds everytime with ( Object reference not set to an
instance of an object. (500) )
Exception.

How can that Exception be thrown?

` var userStory = self.Parent;

            (double)userStory["Microsoft.VSTS.Scheduling.CompletedWork"] =
                userStory.Children.Sum(task =>
task.GetField<double>("Microsoft.VSTS.Scheduling.CompletedWork", 0d));
            (double)userStory["Microsoft.VSTS.Scheduling.OriginalEstimate"] =
                userStory.Children.Sum(taskk =>
taskk.GetField<double>("Microsoft.VSTS.Scheduling.OriginalEstimate",
0d));

`

The Code is very Simple and even provides an default Value.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tfsaggregator/tfsaggregator-webhooks/issues/11>, or mute
the thread

**Comment by Crashdummyy** [comment]
it does have a Parent.
And the Code does what it should.

The only Problem is that it throws this Error.

I will try again with checking for parent

**Comment by giuliov** [comment]
remove the `(double)` cast

**Comment by Crashdummyy** [comment]
Don't know if that was the Problem ( will not find out :smile: )
I'm additionally checking the Parent for the Valid field ( if there is no Parent, there is no valid field of course ).

Code Seems to work fine now

**Comment by Crashdummyy** [comment]
The Double Cast was already removed before
Casting has led me to false results, too.

**Comment by jessehouwing** [comment]
It should be relatively easy to add a validation wrapper for getfield to
log additional debug data when requesting a field that doesn't exist. Then
log the work item type you're actually inspecting.

**Comment by Crashdummyy** [comment]
You're Right should have done that already :/
Because that "Workaround" I did won't work for an additional Custom field.
`TF26027: A field definition Microsoft.VSTS.Scheduling.StoryPoints in the work item type definition file does not exist. Add a definition for this field or remove the reference to the field and try again. (500)`

Is the next Error so I need to add some getField Validators.
Will do that on monday ;)
