### ISSUE TITLE
Deployment Failed

### ISSUE THREAD

**Issue by naspinski** [tfsaggregator/tfsaggregator-webhooks#13]
Similar to https://github.com/tfsaggregator/tfsaggregator-webhooks/issues/8 

I am able to deploy the main branch just fine so I wouldn;t think it would be a permissions issue (https://deploy.azure.com/?repository=https://github.com/tfsaggregator/tfsaggregator-webhooks#/form/setup)

![failed](https://user-images.githubusercontent.com/835597/34420698-919eca5a-ebd0-11e7-9689-ec3d932272c7.PNG)

Any Ideas?

**Comment by naspinski** [comment]
This also happens on the release-2.3 branch as well.

**Comment by naspinski** [comment]
Also, nothing shows up in the Resource Group's deployments log.

**Comment by giuliov** [comment]
Sometimes it succeeds, sometime fails: I haven't find a cause for it.

**Comment by naspinski** [comment]
No, it just never works :(

Without the 2.3 build working, there is no way to use an authenticated connection.

**Comment by codeknox** [comment]
Is this still broken?

![image](https://user-images.githubusercontent.com/5169451/36570033-0fd13d32-17e5-11e8-98e3-81a55f9c80a3.png)

What should I do to install the plugin?

**Comment by jessehouwing** [comment]
It's probably a permissions issue. The deployment is working for some. You
can always manually publish from source.

**Comment by codeknox** [comment]
The issue is that it is not as simple as just pressing the button here:
https://github.com/tfsaggregator/tfsaggregator-webhooks#readme

maybe this page should be edited to not let us believe it is just "press the button". :)

After poking around the documentation for a while, instructions on this page actually unblocked me and I could install by pressing the button:

https://tfsaggregator.github.io/admin/install-webhooks/

**Comment by giuliov** [comment]
I am sorry that you faced such issues, but when I try it succeed, so we need more details to identify the cause. It could be the Azure Region, your permission on AAD or else. Can you share the deployment log from Azure (use the email in case there is sensitive data you do not want make public)?
