### ISSUE TITLE
Not picking up changed policyFilePath

### ISSUE THREAD

**Issue by jdshkolnik** [tfsaggregator/tfsaggregator-webhooks#20]
Hi,

I edited web.config to have a different static value for policyFilePath but it still keeps looking to HelloWorld.policies, even after I restarted the app service.

**Comment by codeknox** [comment]
I have exactly the same issue.
Any workarounds?

**Comment by jdshkolnik** [comment]
I just kept using the original HelloWorld file.

**Comment by andrew-seatonpartners** [comment]
the only way I got this working when deploying to Azure was to ensure that the different name was specified at the point of deploying with the app

**Comment by tireyjp** [comment]
This is due to the deploy adding an appsettings override to the AppService itself. If you open your web hooks AppService in Azure, then go to the "Application settings" tab you will see the policyfile entry that was created during the deploy. This will override anything you place in the web.config. So you can either update the value here, or just delete it so it uses what is in the web.config.
